### ISSUE TITLE
kURL installation in Amazon linux 2 breaks less command 

### ISSUE THREAD

**Issue by tbenattar** [replicatedhq/kURL#2660]
The following error was observed when executing less command after kURL installation finished.

less: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

**Comment by jdtate101** [comment]
This is to do with missing libraries. 

The libtinfo.so.5 library is missing. This is often due to older library version names being referenced and it breaks the app requirements. As AL2 is centos based there might be a newer version of the library.

I've checked my AL2 install (home lab) and it doesn't include the libtinfo.so.5 file, it does however include the libtinfo.so.6 file which is a more recent version. In theory a symbolic link could fix the issue:

sudo ln -s /usr/lib64/libtinfo.so.6 /usr/lib64/libtinfo.so.5

**Comment by aviorma** [comment]
Hi @jdtate101 
This is breaking our AM2 instances using the latest AMI provided by AWS 
We are paying customers and we need this to be fixed ASAP
Thanks 
cc @Joe2daB

**Comment by trelore** [comment]
Hey @tbenattar thanks for raising this issue. This should be fixed by this PR being release https://github.com/replicatedhq/kURL/pull/2936
