### ISSUE TITLE
K8s Memory can be 2Gig but getting a fail and cant complete.

### ISSUE THREAD

**Issue by gmcruz** [replicatedhq/kURL#3966]
Running "cat install.sh | sudo bash -s airgap" I am getting a preflight error that I need 4 Gi Memory but that is not true 2 Gi is stated all over K8s Documentation. I have 2 gigs on my control plane node.

Error:
  [FAIL] Amount of Memory: At least 4G of memory is required, and 8G of memory is recommended

**Comment by rrpolanco** [comment]
Hi @gmcruz, we document 4Gi of Memory as the minimum requirement because we presume you'll be installing the default kURL [manifest](https://kurl.sh/). You can ignore the host preflight checks by specifying the [`exclude-builtin-host-preflights`](https://kurl.sh/docs/install-with-kurl/advanced-options) flag in your installation script like so: `cat install.sh | sudo bash -s airgap exclude-builtin-host-preflights`.

**Comment by camilamacedo86** [comment]
Hi @gmcruz,

I am closing this one as sorted out with the above message.
However, please feel free to open another issue if you need.
