### ISSUE TITLE
Uninstall Kurl

### ISSUE THREAD

**Issue by namgk** [replicatedhq/kURL#4286]
How do we uninstall kurl?

We need to try different kurl bundle and haven't found a way to uninstall previous one.

**Comment by rrpolanco** [comment]
Hi @namgk 
At the moment we don't fully support completely removing/purging a kURL installation. However, we do provide a "best effort" script that will remove Kubernetes packages and host files: https://kurl.sh/docs/install-with-kurl/managing-nodes#reset-a-node. You can give this a try and attempt to install another kURL spec.

Please note the following:
> Do not attempt to reset a node on a cluster in a production environment. Attempting to reset a node can permanently damage the cluster, which makes any data from the cluster irretrievable. Reset a node on a cluster only if you are able to delete the host VM and provision a new VM if the reset script does not successfully complete.

**Comment by camilamacedo86** [comment]
Hi @namgk,

Just to supplement, since you say that you need try I would recommend create new VM/instances to test out each install.
Based in the above answer which provides the info (https://github.com/replicatedhq/kURL/issues/4286#issuecomment-1487535290) I am closing this one. However, feel free to re-open it or open new issues if you need to.
